# Generated by Django 5.1.3 on 2024-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_animes',
            field=models.ManyToManyField(blank=True, to='anime.anime'),
        ),
    ]
