# Generated by Django 5.1.3 on 2024-12-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_userpreference_watched_animes_and_more'),
        ('users', '0004_userpreference_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watched_animes',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='anime.anime'),
        ),
    ]
